name: Bug Report
description: Segnala un malfunzionamento del plugin.
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Grazie per aver deciso di aiutarci a migliorare il plugin!
  - type: input
    id: contact
    attributes:
      label: Dettagli di contatto
      description: Come possiamo contattarti se servono info?
      placeholder: es. email@esempio.it
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: Cosa è successo?
      description: Descrivi il problema e cosa ti aspettavi succedesse.
      placeholder: Raccontaci i dettagli...
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Versione
      description: Quale versione del plugin stai usando?
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
      default: 0
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: Su quali browser riscontri il problema?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Log di errore
      description: Incolla qui eventuali log (verranno formattati automaticamente).
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Codice di Condotta
      options:
        - label: Accetto di seguire le linee guida di questo progetto
          required: true