name: "🐛 Bug Report"
description: Report a bug in omni_video_player.
title: "[BUG]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        <br> Thanks for reporting! Please provide as much detail as possible so we can reproduce the issue.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Initialize omni_video_player with URL...
        2. Call play()...
        3. See error...
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: Affected Platform
      multiple: true
      options:
        - Android
        - iOS
        - Web
    validations:
      required: true
  - type: input
    id: flutter_version
    attributes:
      label: Flutter Version
      placeholder: "Flutter 3.19.0"
    validations:
      required: true
  - type: input
    id: plugin_version
    attributes:
      label: Plugin Version
      placeholder: "Plugin 1.2.0"
    validations:
      required: true
  - type: input
    id: video_format
    attributes:
      label: Video Format/Source
      placeholder: "e.g., Network URL (HTTP/HTTPS/.m3u8/webm) / Youtube (webview or not) / Vimeo / Local File Path / Assets"
    validations:
      required: false
  - type: textarea
    id: doctor
    attributes:
      label: Flutter Doctor Output
      description: Please paste the output of `flutter doctor -v`.
      render: shell
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Paste relevant logs or console output.
      render: shell
  - type: textarea
    id: visual_proof
    attributes:
      label: Screenshots / Video
      description: Drag and drop screenshots or screen recordings here.
    validations:
      required: false